DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(255) UNIQUE NOT NULL,
	`hashedpasswd` BINARY(64) NOT NULL,
	`permissions` INT UNSIGNED NOT NULL 
) ENGINE=InnoDB;
