DROP TABLE IF EXISTS `entityownershipComponents`;
DROP TABLE IF EXISTS `userownershipComponents`;
DROP TABLE IF EXISTS `physicsComponents`;
DROP TABLE IF EXISTS `statisticsComponents`;
DROP TABLE IF EXISTS `itemcontainerComponents`;
DROP TABLE IF EXISTS `locationComponents`;
DROP TABLE IF EXISTS `descriptionComponents`;
DROP TABLE IF EXISTS `Entities`;
DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(255) UNIQUE NOT NULL,
	`hashedpasswd` BINARY(64) NOT NULL,
	`permissions` SMALLINT UNSIGNED NOT NULL,
	INDEX (`username`)
) ENGINE=InnoDB;

CREATE TABLE `Entities` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`type` VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `descriptionComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`summary` VARCHAR(1024) NOT NULL,
	`description` VARCHAR(1024) NOT NULL,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `locationComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`xpos` INT NOT NULL,
	`ypos` INT NOT NULL,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
	INDEX (`xpos`),
	INDEX (`ypos`)
) ENGINE=InnoDB;

CREATE TABLE `itemcontainerComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`capacity` INT UNSIGNED NOT NULL,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `statisticsComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`strength` INT NOT NULL,
	`constitution` INT NOT NULL,
	`dexterity` INT NOT NULL,
	`intelligence` INT NOT NULL,
	`wisdom` INT NOT NULL,
	`charisma` INT NOT NULL,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `physicsComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`volume` INT UNSIGNED NOT NULL,
	`mass` INT UNSIGNED NOT NULL,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `userownershipComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`user_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON UPDATE CASCADE,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `entityownershipComponents` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`owner_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`owner_id`) REFERENCES `Entities` (`id`) ON UPDATE CASCADE,
	`entity_id` INT UNSIGNED NOT NULL,
	FOREIGN KEY (`entity_id`) REFERENCES `Entities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

INSERT INTO `Users` VALUES (NULL, "root", 0x0, 65535);
INSERT INTO `Users` VALUES (NULL, "dasterin", 0x7a3eff4c26e221298cab1d5dfb39ccd7ca8c199291e40c327feae06f91c3bb36e10a618328bf88d91e283bd3d1fe4acc14c2e50ae4b1c51ed754579c6a302173, 65535);